### ISSUE TITLE
Fix Lorax cleanup to not re-install RPMs

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#106]
Commenting out the cleanup call in src/pylorax/\_\_init\_\_.py `rb.cleanup()` gets rid of the issue of removing and reinstalling packages every time, but the size of the image grows with each rebuild. This suggests that there may be other files that actually need to be removed.

Cleanup is defined  by a template in share/runtime-cleanup.tmpl. Create a new share/clip-runtime-cleanup.tmpl, which cleans up only what is necessary. Get rid of unnecessary `removepkg` entries in the new tmpl file.

This should drastically improve build times.

**Comment by ykhodorkovskiy** [comment]
After comparing diffs, LiveOS/squashfs.img is the file that is twice the size when not cleaning up.

**Comment by ykhodorkovskiy** [comment]
install.img == squashfs.img. That file is copied over in x86.tmpl.
