### ISSUE TITLE
Figure out if we need pkgSacks for all arches

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#107]
Currently, Pungi shows this message in the build process:
<pre>Pungi:INFO: Getting sacks for arches <b>['x86_64', 'noarch', 'src']</b></pre>

Yum is being initialized in Pungi's BuildInstall (pypungi/\_\_init\_\_.py::doBuildInstall) with the "archlist" shown <b>above</b> right before Lorax is called. This results in downloading and installing some packages which may not be necessary. 
- [ ] Research whether or not we need to carry the noarch and src sacks.
- [ ] If necessary determine how we can filter these out.

**Comment by ykhodorkovskiy** [comment]
Some packages require noarch rpms. If I remove noarch, then the build fails.

Removing src also had no impact on the build time.
With source:
```
real    8m28.872s
```

without src
```
real 8m39.6838s
```
