### ISSUE TITLE
Don't keep a package list of clip rpms

### ISSUE THREAD

**Issue by ykhodorkovskiy** [TresysTechnology/clip#114]
Since these are RPMs that we generate, and frequently update, it doesn't make sense to keep a static list of versions. See the comment on #36 for more information.

**Comment by sshimko** [comment]
OK, so a series of commits from our tree might be useful as a reference:
967e48720b2c3c959927f2894fbc9d14b2e4293a
ee016164592938d7647d84346361088688957751
a96eed69bdebdcd30e034c58d2e14b416974efb3

And tangentially related from my tree:
d73d761799cb79c0d0dff34cd28e56272bdf9759
