### ISSUE TITLE
Resolve kernel denials

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#126]
In order to get this system booting in Enforcing, we will need to resolve the remaining kernel_t denials.

Assumptions:
- Work will be done off of mpalmi/clip@95bafa004072cff0cfef3bf12e7357e0f1ad998b
- Allow rules are needed to get CLIP booting in Enforcing
- Least privilege access model will be employed
- refpolicy guidelines for policy [development](https://github.com/TresysTechnology/refpolicy/wiki/Documentation) will be followed.

Subtasks:
- [ ] Ensure all files are properly labeled
- [x] Resolve logging denials
- [x] Resolve shutdown denials
- [x] Resolve user/login denials

----

audit2allow
<pre>
#============= audisp_t ==============
allow audisp_t kernel_t:unix_dgram_socket sendto;

#============= kernel_t ==============
allow kernel_t device_t:chr_file setattr;

#============= local_login_t ==============
allow local_login_t kernel_t:unix_dgram_socket sendto;

#============= shutdown_t ==============
allow shutdown_t kernel_t:dir search;
allow shutdown_t kernel_t:fd use;

#============= staff_t ==============
allow staff_t kernel_t:unix_dgram_socket sendto;
</pre>

audit.log
<pre>
9:type=AVC msg=audit(1429891501.774:815): avc:  denied  { sendto } for  pid=1336 comm="sshd" path="/dev/log" scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:system_r:kernel_t:s0 tclass=unix_dgram_socket
32:type=AVC msg=audit(1429891501.786:830): avc:  denied  { sendto } for  pid=613 comm="login" path="/dev/log" scontext=system_u:system_r:local_login_t:s0-s0:c0.c1023 tcontext=system_u:system_r:kernel_t:s0 tclass=unix_dgram_socket
146:type=AVC msg=audit(1429891520.613:241): avc:  denied  { sendto } for  pid=690 comm="audispd" path="/dev/log" scontext=system_u:system_r:audisp_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=unix_dgram_socket
159:type=AVC msg=audit(1429891528.563:249): avc:  denied  { use } for  pid=1 comm="systemd-shutdow" path="/dev/null" dev="devtmpfs" ino=4483 scontext=system_u:system_r:shutdown_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=fd
161:type=AVC msg=audit(1429891528.565:251): avc:  denied  { search } for  pid=1 comm="systemd-shutdow" name="2" dev="proc" ino=8384 scontext=system_u:system_r:shutdown_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=dir
226:type=AVC msg=audit(1429891544.501:232): avc:  denied  { sendto } for  pid=587 comm="audispd" path="/dev/log" scontext=system_u:system_r:audisp_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=unix_dgram_socket
242:type=AVC msg=audit(1429891545.610:246): avc:  denied  { setattr } for  pid=14 comm="kdevtmpfs" name="vcs6" dev="devtmpfs" ino=13420 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:device_t:s0 tclass=chr_file
243:type=AVC msg=audit(1429891545.612:247): avc:  denied  { setattr } for  pid=14 comm="kdevtmpfs" name="vcsa6" dev="devtmpfs" ino=13430 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:device_t:s0 tclass=chr_file
</pre>

**Comment by mpalmi** [comment]
Only remaining denial here is:
<pre>
type=AVC msg=audit(1430921872.323:143): avc:  denied  { setattr } for  pid=14 comm="kdevtmpfs" name="vcs6" dev="devtmpfs" ino=13401 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:device_t:s0 tclass=chr_file

#============= kernel_t ==============
allow kernel_t device_t:chr_file setattr;
</pre>

It only appears once and is likely happening before the file gets labeled (which it does).
Hopefully this is enough to get CLIP booting in Enforcing.

**Comment by ykhodorkovskiy** [comment]
@mpalmi I added the following 2 allow rules and did not see anymore denials. What do you think?

```
+allow kernel_t device_t:chr_file setattr;
+allow kernel_t device_t:blk_file setattr;
```

**Comment by mpalmi** [comment]
I don't think this is the right path. I'd imagine we don't want these files labeled as generic device_t files.
IF you were to allow these perms, you'd probably do it with an interface that's already defined.
I'll look into this one.

**Comment by mpalmi** [comment]
Looking at the denial:
> type=AVC msg=audit(1438183381.970:58): avc:  denied  { setattr } for  pid=14 comm="kdevtmpfs" name="event4" dev="devtmpfs" ino=10145 scontext=system_u:system_r:kernel_t:s0 tcontext=system_u:object_r:device_t:s0 tclass=chr_file

The "name" field is event4, which aligns with the chr_file:
>[root@localhost dev]# ls -lZ /dev/input/event4
crw-------. root root system_u:object_r:event_device_t:s0 /dev/input/event4

rhel7 targeted policy has:
```+########################################
+## <summary>
+##     Create all named devices with the correct label
+## </summary>
+## <param name="domain">
+##     <summary>
+##      Domain allowed access.
+##     </summary>
+## </param>
+#
+interface(`dev_filetrans_all_named_dev',`
<snip>
+       filetrans_pattern($1, device_t, event_device_t, chr_file, "event0")
+       filetrans_pattern($1, device_t, event_device_t, chr_file, "event1")
+       filetrans_pattern($1, device_t, event_device_t, chr_file, "event2")
+       filetrans_pattern($1, device_t, event_device_t, chr_file, "event3")
+       filetrans_pattern($1, device_t, event_device_t, chr_file, "event4")
<snip>
```

In this interface, they explicitly call out 45 named devices. I'm this doesn't seem like the right way to go, but in the case of emergency, we can attempt to implement a cleaner version of this approach.

**Comment by ykhodorkovskiy** [comment]
There are no more kernel_t denials as of 9bb181e

**Comment by doverride** [comment]
What kdevtmpfs creates often depends on your hardware. So testing it on various systems with various periperials helps catch more of these kdevtmpfs issues. Common things are the various models of sound devices, mouse device, tpm, mei, printer device. removable storage devices etc
