### ISSUE TITLE
Resolve initrc_t denials

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#127]
In order to get this system booting in Enforcing, we will need to resolve the remaining kernel_t denials.

Assumptions:
- Work will be done off of mpalmi/clip@95bafa004072cff0cfef3bf12e7357e0f1ad998b
- Allow rules are needed to get CLIP booting in Enforcing
- Least privilege access model will be employed
- refpolicy guidelines for policy [development](https://github.com/TresysTechnology/refpolicy/wiki/Documentation) will be followed.

Subtasks:
- [x] Ensure all files are properly labeled
- [x] Resolve init_t unix_stream_socket denials
- [x] Resolve pidfile denials

----

audit2allow
<pre>
#============= initrc_t ==============
allow initrc_t init_t:unix_stream_socket { read write ioctl getattr };
allow initrc_t init_var_lib_t:file setattr;
allow initrc_t initrc_var_run_t:dir { create setattr };
</pre>

audit.log
<pre>
50:type=SYSCALL msg=audit(1429891501.882:845): arch=c000003e syscall=59 success=yes exit=0 a0=7f7c5f678210 a1=7f7c5f7af2f0 a2=7f7c5f7c0000 a3=ffffffff items=0 ppid=1 pid=2015 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-user-se" exe="/usr/lib/systemd/systemd-user-sessions" subj=system_u:system_r:initrc_t:s0 key=(null)
52:type=AVC msg=audit(1429891501.884:847): avc:  denied  { ioctl } for  pid=2015 comm="systemd-user-se" path="socket:[16953]" dev="sockfs" ino=16953 scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket
53:type=SYSCALL msg=audit(1429891501.884:847): arch=c000003e syscall=16 success=no exit=-25 a0=2 a1=5401 a2=7ffff754f8c0 a3=7ffff754fa70 items=0 ppid=1 pid=2015 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-user-se" exe="/usr/lib/systemd/systemd-user-sessions" subj=system_u:system_r:initrc_t:s0 key=(null)
55:type=AVC msg=audit(1429891501.890:849): avc:  denied  { getattr } for  pid=2016 comm="network" path="socket:[17001]" dev="sockfs" ino=17001 scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket
56:type=SYSCALL msg=audit(1429891501.890:849): arch=c000003e syscall=4 success=yes exit=0 a0=23a5540 a1=7fff26341dc0 a2=7fff26341dc0 a3=7fff26341b70 items=0 ppid=1 pid=2016 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="network" exe="/usr/bin/bash" subj=system_u:system_r:initrc_t:s0 key=(null)
57:type=AVC msg=audit(1429891502.023:850): avc:  denied  { create } for  pid=2037 comm="cpio" name="run" scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:object_r:initrc_var_run_t:s0 tclass=dir
58:type=SYSCALL msg=audit(1429891502.023:850): arch=c000003e syscall=83 success=yes exit=0 a0=13d4650 a1=41ed a2=2 a3=7fffe5e2eb60 items=0 ppid=2014 pid=2037 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="cpio" exe="/usr/bin/cpio" subj=system_u:system_r:initrc_t:s0 key=(null)
59:type=AVC msg=audit(1429891502.023:851): avc:  denied  { setattr } for  pid=2037 comm="cpio" name="run" dev="tmpfs" ino=17082 scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:object_r:initrc_var_run_t:s0 tclass=dir
60:type=SYSCALL msg=audit(1429891502.023:851): arch=c000003e syscall=92 success=yes exit=0 a0=13d4650 a1=0 a2=0 a3=7fffe5e2eb60 items=0 ppid=2014 pid=2037 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="cpio" exe="/usr/bin/cpio" subj=system_u:system_r:initrc_t:s0 key=(null)
72:type=AVC msg=audit(1429891502.724:859): avc:  denied  { setattr } for  pid=2209 comm="systemd-random-" name="random-seed" dev="dm-8" ino=129586 scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:object_r:init_var_lib_t:s0 tclass=file
73:type=SYSCALL msg=audit(1429891502.724:859): arch=c000003e syscall=91 success=yes exit=0 a0=4 a1=180 a2=180 a3=ffffffe0 items=0 ppid=1 pid=2209 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-random-" exe="/usr/lib/systemd/systemd-random-seed" subj=system_u:system_r:initrc_t:s0 key=(null)
75:type=SYSTEM_SHUTDOWN msg=audit(1429891502.755:861): pid=2208 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 msg='init exe="/usr/lib/systemd/systemd-update-utmp" hostname=? addr=? terminal=? res=success'
138:type=AVC msg=audit(1429891516.167:61): avc:  denied  { read write } for  pid=400 comm="mkdir" path="socket:[8922]" dev="sockfs" ino=8922 scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket
139:type=SYSCALL msg=audit(1429891516.167:61): arch=c000003e syscall=59 success=yes exit=0 a0=7f6c66370080 a1=7f6c663826f0 a2=7f6c66383af0 a3=ffffffff items=0 ppid=1 pid=400 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="mkdir" exe="/usr/bin/mkdir" subj=system_u:system_r:initrc_t:s0 key=(null)
144:type=SYSTEM_BOOT msg=audit(1429891520.593:239): pid=674 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 msg='init exe="/usr/lib/systemd/systemd-update-utmp" hostname=? addr=? terminal=? res=success'
223:type=AVC msg=audit(1429891540.170:61): avc:  denied  { read write } for  pid=401 comm="mkdir" path="socket:[8843]" dev="sockfs" ino=8843 scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket
224:type=SYSCALL msg=audit(1429891540.170:61): arch=c000003e syscall=59 success=yes exit=0 a0=7f013b525080 a1=7f013b5376f0 a2=7f013b538af0 a3=ffffffff items=0 ppid=1 pid=401 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="mkdir" exe="/usr/bin/mkdir" subj=system_u:system_r:initrc_t:s0 key=(null)
232:type=SYSTEM_BOOT msg=audit(1429891544.600:236): pid=597 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 msg='init exe="/usr/lib/systemd/systemd-update-utmp" hostname=? addr=? terminal=? res=success'
244:type=AVC msg=audit(1429891545.665:248): avc:  denied  { getattr } for  pid=672 comm="grep" path="socket:[12639]" dev="sockfs" ino=12639 scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket
245:type=SYSCALL msg=audit(1429891545.665:248): arch=c000003e syscall=5 success=yes exit=0 a0=1 a1=7fffcd9faf80 a2=7fffcd9faf80 a3=7fffcd9face0 items=0 ppid=636 pid=672 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="grep" exe="/usr/bin/grep" subj=system_u:system_r:initrc_t:s0 key=(null)
246:type=AVC msg=audit(1429891545.665:249): avc:  denied  { ioctl } for  pid=672 comm="grep" path="socket:[12639]" dev="sockfs" ino=12639 scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket
247:type=SYSCALL msg=audit(1429891545.665:249): arch=c000003e syscall=16 success=no exit=-25 a0=1 a1=5401 a2=7fffcd9fae90 a3=7fffcd9face0 items=0 ppid=636 pid=672 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="grep" exe="/usr/bin/grep" subj=system_u:system_r:initrc_t:s0 key=(null)
248:type=AVC msg=audit(1429891545.887:250): avc:  denied  { write } for  pid=599 comm="network" path="socket:[12639]" dev="sockfs" ino=12639 scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket
249:type=SYSCALL msg=audit(1429891545.887:250): arch=c000003e syscall=1 success=yes exit=1 a0=1 a1=7ff2ecdd4000 a2=1 a3=1 items=0 ppid=1 pid=599 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="network" exe="/usr/bin/bash" subj=system_u:system_r:initrc_t:s0 key=(null)
885:type=AVC msg=audit(1429891549.541:568): avc:  denied  { read } for  pid=1237 comm="systemd-update-" path="socket:[14978]" dev="sockfs" ino=14978 scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket
886:type=SYSCALL msg=audit(1429891549.541:568): arch=c000003e syscall=59 success=yes exit=0 a0=7f013b531f80 a1=7f013b3f6890 a2=7f013b3c6230 a3=ffffffff items=0 ppid=1 pid=1237 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-update-" exe="/usr/lib/systemd/systemd-update-utmp" subj=system_u:system_r:initrc_t:s0 key=(null)
887:type=SYSTEM_RUNLEVEL msg=audit(1429891549.543:569): pid=1237 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:initrc_t:s0 msg='old-level=N new-level=3 exe="/usr/lib/systemd/systemd-update-utmp" hostname=? addr=? terminal=? res=success'
</pre>

**Comment by mpalmi** [comment]
@tomhurd Could you please review these changes?

**Comment by mpalmi** [comment]
Some autorelabel denials seen. We may be okay just ignoring these, but posting here for discussion/posterity:

>#============= initrc_t ==============
allow initrc_t root_t:file open;
allow initrc_t security_t:file write;

<pre>
type=AVC msg=audit(1432156309.859:84): avc:  denied  { write } for  pid=567 comm="rhel-autorelabe" name="enforce" dev="selinuxfs" ino=4 scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:object_r:security_t:s0 tclass=file
type=AVC msg=audit(1432156309.863:85): avc:  denied  { open } for  pid=586 comm="cat" path="/.autorelabel" dev="dm-1" ino=14 scontext=system_u:system_r:initrc_t:s0 tcontext=root:object_r:root_t:s0 tclass=file
type=AVC msg=audit(1432156309.859:84): avc:  denied  { write } for  pid=567 comm="rhel-autorelabe" name="enforce" dev="selinuxfs" ino=4 scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:object_r:security_t:s0 tclass=file
type=AVC msg=audit(1432156309.863:85): avc:  denied  { open } for  pid=586 comm="cat" path="/.autorelabel" dev="dm-1" ino=14 scontext=system_u:system_r:initrc_t:s0 tcontext=root:object_r:root_t:s0 tclass=file
</pre>

**Comment by tomhurd** [comment]
Some ideas for the security_t:file write denial
1. Create a new domain that has the permissions and transition to it
2. Transition to setfiles_t - not sure if this will require more tweaking
3. selinux_set_enforce_mode(initrc_t) - the thing I don't like about this is sysadm_t has write permissions to files that transition to initrc_t.  But those permissions should be removed anyway.

**Comment by ykhodorkovskiy** [comment]
No denials seen

**Comment by mpalmi** [comment]
Only remaining denials should be for aide service.
