### ISSUE TITLE
Resolve syslogd_t denials

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#129]
In order to get this system booting in Enforcing, we will need to resolve the remaining kernel_t denials.

Assumptions:
- Work will be done off of mpalmi/clip@95bafa004072cff0cfef3bf12e7357e0f1ad998b
- Allow rules are needed to get CLIP booting in Enforcing
- Least privilege access model will be employed
- refpolicy guidelines for policy [development](https://github.com/TresysTechnology/refpolicy/wiki/Documentation) will be followed.

Subtasks:
- [x] Figure out what is being denied
- [x] Ensure that files are properly labeled
- [x] Add policy to get this domain Enforcing

----

There are currently no denials seen for syslogd_t in permissive.

**Comment by mpalmi** [comment]
@tomhurd Could you review these please?
- [ ] mpalmi/clip@eef0e53
- [ ] mpalmi/clip@9bc516b

**Comment by ykhodorkovskiy** [comment]
No denials seen
