### ISSUE TITLE
Resolve udev_t denials

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#130]
In order to get this system booting in Enforcing, we will need to resolve the remaining kernel_t denials.

Assumptions:
- Work will be done off of mpalmi/clip@95bafa004072cff0cfef3bf12e7357e0f1ad998b
- Allow rules are needed to get CLIP booting in Enforcing
- Least privilege access model will be employed
- refpolicy guidelines for policy [development](https://github.com/TresysTechnology/refpolicy/wiki/Documentation) will be followed.

Subtasks:
- [ ] Figure out what is being denied
- [x] Ensure that files are properly labeled
- [x] Add policy to get this domain Enforcing

----

There are currently no denials seen for udev_t in permissive.

**Comment by mpalmi** [comment]
The only denial seen on first-boot is:
> #============= udev_t ==============
allow udev_t modules_object_t:file getattr;

<pre>
type=AVC msg=audit(1430925422.060:188): avc:  denied  { getattr } for  pid=438 comm="systemd-udevd" path="/usr/lib/modules/3.10.0-123.el7.x86_64/modules.dep.bin" dev="dm-1" ino=136905 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:object_r:modules_object_t:s0 tclass=file
</pre>

@tomhurd Please verify that this is resolved by mpalmi/clip@8961b68

**Comment by mpalmi** [comment]
Now seeing the following denials:

<pre>
allow udev_t init_t:unix_dgram_socket sendto;
allow udev_t self:capability sys_module;
</pre>

<pre>
type=AVC msg=audit(1432138293.808:54): avc:  denied  { sendto } for  pid=432 comm="systemd-udevd" path=002F6F72672F667265656465736B746F702F73797374656D64312F6E6F74696679 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:system_r:init_t:s0 tclass=unix_dgram_socket
type=AVC msg=audit(1432138293.885:57): avc:  denied  { sys_module } for  pid=444 comm="systemd-udevd" capability=16  scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tclass=capability
type=AVC msg=audit(1432138309.799:52): avc:  denied  { sendto } for  pid=427 comm="systemd-udevd" path=002F6F72672F667265656465736B746F702F73797374656D64312F6E6F74696679 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:system_r:init_t:s0 tclass=unix_dgram_socket
type=AVC msg=audit(1432138309.866:56): avc:  denied  { sys_module } for  pid=441 comm="systemd-udevd" capability=16  scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tclass=capability
type=AVC msg=audit(1432138309.799:52): avc:  denied  { sendto } for  pid=427 comm="systemd-udevd" path=002F6F72672F667265656465736B746F702F73797374656D64312F6E6F74696679 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:system_r:init_t:s0 tclass=unix_dgram_socket
type=AVC msg=audit(1432138293.808:54): avc:  denied  { sendto } for  pid=432 comm="systemd-udevd" path=002F6F72672F667265656465736B746F702F73797374656D64312F6E6F74696679 scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:system_r:init_t:s0 tclass=unix_dgram_socket

**Comment by mpalmi** [comment]
I thought the sys_module capability was fishy for udev to have...
If I'm not mistaken, other processes should be responsible for removing/loading kernel modules.

At any rate, there's a neverallow for that permission. If this is problematic in achieving a clean boot, we should either raise issue for a code change, or attempt to address this another way.

**Comment by ykhodorkovskiy** [comment]
```
type=AVC msg=audit(1432632038.653:57): avc:  denied  { sys_module } for  pid=652 comm="systemd-udevd" capability=16  scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tclass=capability
type=AVC msg=audit(1432632081.720:57): avc:  denied  { sys_module } for  pid=655 comm="systemd-udevd" capability=16  scontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tcontext=system_u:system_r:udev_t:s0-s0:c0.c1023 tclass=capability
```

`allow udev_t self:capability sys_module;`

**Comment by mpalmi** [comment]
Added to the watchlist until we figure out if/why this sys_module permission is needed.

**Comment by mpalmi** [comment]
Figure out why udev_t is attempting to directly load/remove kernel modules, rather than going through kmod or something similar.

**Comment by ykhodorkovskiy** [comment]
@mpalmi I'm not sure I see where this is being called in the systemd code. What's a good way to debug this?

I found in udev-buildin-kmod.c the libkmod api is called to load some modules, so that seems correct. I couldn't track down the PID in the denial on my system since the process no longer existed after boot.

**Comment by mpalmi** [comment]
Merged.
