### ISSUE TITLE
Resolve insmod_t denials

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#132]
In order to get this system booting in Enforcing, we will need to resolve the remaining kernel_t denials.

Assumptions:
- Work will be done off of mpalmi/clip@95bafa004072cff0cfef3bf12e7357e0f1ad998b
- Allow rules are needed to get CLIP booting in Enforcing
- Least privilege access model will be employed
- refpolicy guidelines for policy [development](https://github.com/TresysTechnology/refpolicy/wiki/Documentation) will be followed.

Subtasks:
- [x] Ensure all files are properly labeled
- [x] Allow insmod to write/getattr/open /run/tmpfiles.d/kmod.conf
- [x] Allow insmod to r/w to iptables sockets

----

audit2allow
<pre>
#============= insmod_t ==============
allow insmod_t init_t:unix_stream_socket { read write };
allow insmod_t iptables_t:rawip_socket { read write };
allow insmod_t iptables_t:unix_stream_socket { read write };
allow insmod_t var_run_t:file { write getattr open };
</pre>

audit.log
<pre>
type=AVC msg=audit(1431434394.400:48): avc:  denied  { read write } for  pid=413 comm="kmod" path="socket:[9575]" dev="sockfs" ino=9575 scontext=system_u:system_r:insmod_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket

type=AVC msg=audit(1431434394.435:49): avc:  denied  { write } for  pid=413 comm="kmod" name="kmod.conf" dev="tmpfs" ino=6242 scontext=system_u:system_r:insmod_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file

type=AVC msg=audit(1431434394.435:49): avc:  denied  { open } for  pid=413 comm="kmod" path="/run/tmpfiles.d/kmod.conf" dev="tmpfs" ino=6242 scontext=system_u:system_r:insmod_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file

type=AVC msg=audit(1431434394.436:50): avc:  denied  { getattr } for  pid=413 comm="kmod" path="/run/tmpfiles.d/kmod.conf" dev="tmpfs" ino=6242 scontext=system_u:system_r:insmod_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file

type=AVC msg=audit(1431434414.498:49): avc:  denied  { read write } for  pid=419 comm="kmod" path="socket:[9517]" dev="sockfs" ino=9517 scontext=system_u:system_r:insmod_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket

type=AVC msg=audit(1431434414.542:50): avc:  denied  { write } for  pid=419 comm="kmod" name="kmod.conf" dev="tmpfs" ino=6242 scontext=system_u:system_r:insmod_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file

type=AVC msg=audit(1431434414.542:50): avc:  denied  { open } for  pid=419 comm="kmod" path="/run/tmpfiles.d/kmod.conf" dev="tmpfs" ino=6242 scontext=system_u:system_r:insmod_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file

type=AVC msg=audit(1431434414.543:51): avc:  denied  { getattr } for  pid=419 comm="kmod" path="/run/tmpfiles.d/kmod.conf" dev="tmpfs" ino=6242 scontext=system_u:system_r:insmod_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=file

type=AVC msg=audit(1431434416.553:147): avc:  denied  { read write } for  pid=646 comm="modprobe" path="socket:[13513]" dev="sockfs" ino=13513 scontext=system_u:system_r:insmod_t:s0 tcontext=system_u:system_r:iptables_t:s0 tclass=unix_stream_socket

type=AVC msg=audit(1431434416.751:158): avc:  denied  { read write } for  pid=735 comm="modprobe" path="socket:[13631]" dev="sockfs" ino=13631 scontext=system_u:system_r:insmod_t:s0 tcontext=system_u:system_r:iptables_t:s0 tclass=rawip_socket
</pre>

**Comment by ykhodorkovskiy** [comment]
No denials seen

**Comment by doverride** [comment]
probably only happens when a module is loaded by iptables/nftables

the init_t rw inherited stream sockets are common to all systemd daemon forked processes in my experience.

So iptables service is a systemd daemon that forks kmod/insmod

So kmod needs to rw inherited init_t stream sockets

A systemd daemon forked process is either a daemon of Type=forked or any process indirectly forked (like the example of kmod/iptables above)
