### ISSUE TITLE
Resolve staff_t denials

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#133]
In order to get this system booting in Enforcing, we will need to resolve the remaining kernel_t denials.

Assumptions:
- Work will be done off of mpalmi/clip@95bafa004072cff0cfef3bf12e7357e0f1ad998b
- Allow rules are needed to get CLIP booting in Enforcing
- Least privilege access model will be employed
- refpolicy guidelines for policy [development](https://github.com/TresysTechnology/refpolicy/wiki/Documentation) will be followed.

Subtasks:
- [ ] Ensure all sockets are properly labeled
- [ ] Verify local_login_t policy from #131
- [ ] Write staff policy with least privilege in mind

----

audit2allow
<pre>
#============= sshd_t ==============
allow sshd_t staff_t:key write;
allow sshd_t staff_t:process dyntransition;

#============= local_login_t ==============
allow local_login_t staff_t:key { write search };

#============= staff_t ==============
allow staff_t auditd_log_t:dir search;
allow staff_t auditd_log_t:file { write read getattr open };
allow staff_t init_t:unix_stream_socket connectto;
allow staff_t init_var_run_t:sock_file write;
allow staff_t kernel_t:unix_dgram_socket sendto;
allow staff_t power_unit_file_t:service start;
allow staff_t self:capability { setuid audit_write };
allow staff_t self:netlink_audit_socket { write nlmsg_relay create read };
allow staff_t self:process setcurrent;
allow staff_t sshd_t:tcp_socket { read write getattr setopt getopt };
</pre>

audit.log
<pre>
2:type=AVC msg=audit(1429891501.748:812): avc:  denied  { write } for  pid=1340 comm="bash" name="audit.log" dev="dm-5" ino=12 scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:object_r:auditd_log_t:s0 tclass=file
3:type=AVC msg=audit(1429891501.748:812): avc:  denied  { open } for  pid=1340 comm="bash" path="/var/log/audit/audit.log" dev="dm-5" ino=12 scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:object_r:auditd_log_t:s0 tclass=file
4:type=SYSCALL msg=audit(1429891501.748:812): arch=c000003e syscall=2 success=yes exit=3 a0=819250 a1=241 a2=1b6 a3=0 items=0 ppid=1336 pid=1340 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4 comm="bash" exe="/usr/bin/bash" subj=root:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
5:type=AVC msg=audit(1429891501.754:813): avc:  denied  { write } for  pid=1994 comm="reboot" name="private" dev="tmpfs" ino=8632 scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:object_r:init_var_run_t:s0 tclass=sock_file
6:type=AVC msg=audit(1429891501.754:813): avc:  denied  { connectto } for  pid=1994 comm="reboot" path="/run/systemd/private" scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket
7:type=SYSCALL msg=audit(1429891501.754:813): arch=c000003e syscall=42 success=yes exit=0 a0=3 a1=7fff43b55010 a2=16 a3=7fff43b54dc0 items=0 ppid=1340 pid=1994 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4 comm="reboot" exe="/usr/bin/syst
emctl" subj=root:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
8:type=USER_AVC msg=audit(1429891501.768:814): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='avc:  denied  { start } for auid=0 uid=0 gid=0 path="/usr/lib/systemd/system/reboot.target" cmdline="reboot" scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:object_r:power_unit_file_t:s0 tclass=service  exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'
9:type=AVC msg=audit(1429891501.774:815): avc:  denied  { sendto } for  pid=1336 comm="sshd" path="/dev/log" scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:system_r:kernel_t:s0 tclass=unix_dgram_socket
10:type=SYSCALL msg=audit(1429891501.774:815): arch=c000003e syscall=42 success=yes exit=0 a0=4 a1=7fa55aa0b740 a2=6e a3=1c items=0 ppid=1241 pid=1336 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4 comm="sshd" exe="/usr/sbin/sshd" subj=root:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
11:type=USER_END msg=audit(1429891501.776:816): pid=1336 uid=0 auid=0 ses=4 subj=root:staff_r:staff_t:s0-s0:c0.c1023 msg='op=PAM:session_close acct="root" exe="/usr/sbin/sshd" hostname=10.1.6.214 addr=10.1.6.214 terminal=ssh res=success'
12:type=CRED_DISP msg=audit(1429891501.776:817): pid=1336 uid=0 auid=0 ses=4 subj=root:staff_r:staff_t:s0-s0:c0.c1023 msg='op=PAM:setcred acct="root" exe="/usr/sbin/sshd" hostname=10.1.6.214 addr=10.1.6.214 terminal=ssh res=success'
13:type=USER_END msg=audit(1429891501.778:818): pid=1336 uid=0 auid=0 ses=4 subj=root:staff_r:staff_t:s0-s0:c0.c1023 msg='op=login id=0 exe="/usr/sbin/sshd" hostname=10.1.6.214 addr=10.1.6.214 terminal=ssh res=success'
14:type=USER_LOGOUT msg=audit(1429891501.778:819): pid=1336 uid=0 auid=0 ses=4 subj=root:staff_r:staff_t:s0-s0:c0.c1023 msg='op=login id=0 exe="/usr/sbin/sshd" hostname=10.1.6.214 addr=10.1.6.214 terminal=ssh res=success'
15:type=CRYPTO_KEY_USER msg=audit(1429891501.779:820): pid=1336 uid=0 auid=0 ses=4 subj=root:staff_r:staff_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=df:92:3f:47:a0:92:83:a2:d0:fa:77:fc:78:a6:73:56 direction=? spid=1336 suid=0  exe="/usr/sbin/sshd" hostname=? addr=10.1.6.214 terminal=? res=success'
18:type=AVC msg=audit(1429891501.782:823): avc:  denied  { create } for  pid=1292 comm="sudo" scontext=toor_u:staff_r:staff_t:s0 tcontext=toor_u:staff_r:staff_t:s0 tclass=netlink_audit_socket
19:type=SYSCALL msg=audit(1429891501.782:823): arch=c000003e syscall=41 success=yes exit=0 a0=10 a1=3 a2=9 a3=0 items=0 ppid=1270 pid=1292 auid=1000 uid=0 gid=1000 euid=0 suid=0 fsuid=0 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=2 comm="sudo" exe="/usr/bin/sudo" subj=t
oor_u:staff_r:staff_t:s0 key=(null)
20:type=AVC msg=audit(1429891501.782:824): avc:  denied  { write } for  pid=1292 comm="sudo" scontext=toor_u:staff_r:staff_t:s0 tcontext=toor_u:staff_r:staff_t:s0 tclass=netlink_audit_socket
21:type=AVC msg=audit(1429891501.782:824): avc:  denied  { nlmsg_relay } for  pid=1292 comm="sudo" scontext=toor_u:staff_r:staff_t:s0 tcontext=toor_u:staff_r:staff_t:s0 tclass=netlink_audit_socket
22:type=AVC msg=audit(1429891501.782:824): avc:  denied  { audit_write } for  pid=1292 comm="sudo" capability=29  scontext=toor_u:staff_r:staff_t:s0 tcontext=toor_u:staff_r:staff_t:s0 tclass=capability
23:type=USER_END msg=audit(1429891501.782:825): pid=1292 uid=0 auid=1000 ses=2 subj=toor_u:staff_r:staff_t:s0 msg='op=PAM:session_close acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/tty1 res=success'
24:type=SYSCALL msg=audit(1429891501.782:824): arch=c000003e syscall=44 success=yes exit=120 a0=0 a1=7fff73d878d0 a2=78 a3=0 items=0 ppid=1270 pid=1292 auid=1000 uid=0 gid=1000 euid=0 suid=0 fsuid=0 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=2 comm="sudo" exe="/usr/bin
/sudo" subj=toor_u:staff_r:staff_t:s0 key=(null)
25:type=AVC msg=audit(1429891501.782:826): avc:  denied  { read } for  pid=1292 comm="sudo" scontext=toor_u:staff_r:staff_t:s0 tcontext=toor_u:staff_r:staff_t:s0 tclass=netlink_audit_socket
26:type=SYSCALL msg=audit(1429891501.782:826): arch=c000003e syscall=45 success=yes exit=36 a0=0 a1=7fff73d89c00 a2=231c a3=42 items=0 ppid=1270 pid=1292 auid=1000 uid=0 gid=1000 euid=0 suid=0 fsuid=0 egid=1000 sgid=1000 fsgid=1000 tty=(none) ses=2 comm="sudo" exe="/usr/b
in/sudo" subj=toor_u:staff_r:staff_t:s0 key=(null)
27:type=CRED_DISP msg=audit(1429891501.782:827): pid=1292 uid=0 auid=1000 ses=2 subj=toor_u:staff_r:staff_t:s0 msg='op=PAM:setcred acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/tty1 res=success'
29:type=AVC msg=audit(1429891501.784:829): avc:  denied  { search } for  pid=613 comm="login" scontext=system_u:system_r:local_login_t:s0-s0:c0.c1023 tcontext=toor_u:staff_r:staff_t:s0 tclass=key
30:type=AVC msg=audit(1429891501.784:829): avc:  denied  { write } for  pid=613 comm="login" scontext=system_u:system_r:local_login_t:s0-s0:c0.c1023 tcontext=toor_u:staff_r:staff_t:s0 tclass=key
908:type=USER_ROLE_CHANGE msg=audit(1429891635.001:585): pid=1239 uid=0 auid=0 ses=1 subj=system_u:system_r:sshd_t:s0-s0:c0.c1023 msg='pam: default-context=root:staff_r:staff_t:s0-s0:c0.c1023 selected-context=root:staff_r:staff_t:s0-s0:c0.c1023 exe="/usr/sbin/sshd" hostna
me=10.1.6.214 addr=10.1.6.214 terminal=ssh res=success'
909:type=AVC msg=audit(1429891635.001:586): avc:  denied  { write } for  pid=1239 comm="sshd" scontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=root:staff_r:staff_t:s0-s0:c0.c1023 tclass=key
916:type=AVC msg=audit(1429891635.018:589): avc:  denied  { dyntransition } for  pid=1239 comm="sshd" scontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=root:staff_r:staff_t:s0-s0:c0.c1023 tclass=process
917:type=SYSCALL msg=audit(1429891635.018:589): arch=c000003e syscall=1 success=yes exit=36 a0=5 a1=7f28f437e360 a2=24 a3=31632e30633a3073 items=0 ppid=1235 pid=1239 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1 comm="sshd" exe="/usr/sbin
/sshd" subj=root:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
918:type=AVC msg=audit(1429891635.018:590): avc:  denied  { read } for  pid=1239 comm="sshd" path="socket:[15088]" dev="sockfs" ino=15088 scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tclass=tcp_socket
919:type=SYSCALL msg=audit(1429891635.018:590): arch=c000003e syscall=0 success=yes exit=120 a0=3 a1=7fffb53d1de0 a2=4000 a3=0 items=0 ppid=1235 pid=1239 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1 comm="sshd" exe="/usr/sbin/sshd" subj=
root:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
920:type=AVC msg=audit(1429891635.018:591): avc:  denied  { write } for  pid=1239 comm="sshd" path="socket:[15088]" dev="sockfs" ino=15088 scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tclass=tcp_socket
921:type=SYSCALL msg=audit(1429891635.018:591): arch=c000003e syscall=1 success=yes exit=52 a0=3 a1=7f28f4363cf0 a2=34 a3=0 items=0 ppid=1235 pid=1239 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1 comm="sshd" exe="/usr/sbin/sshd" subj=roo
t:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
922:type=AVC msg=audit(1429891635.019:592): avc:  denied  { create } for  pid=1239 comm="sshd" scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=root:staff_r:staff_t:s0-s0:c0.c1023 tclass=netlink_audit_socket
923:type=SYSCALL msg=audit(1429891635.019:592): arch=c000003e syscall=41 success=yes exit=8 a0=10 a1=3 a2=9 a3=6c2f7261762f202e items=0 ppid=1235 pid=1239 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1 comm="sshd" exe="/usr/sbin/sshd" subj
=root:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
924:type=AVC msg=audit(1429891635.019:593): avc:  denied  { write } for  pid=1239 comm="sshd" scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=root:staff_r:staff_t:s0-s0:c0.c1023 tclass=netlink_audit_socket
925:type=AVC msg=audit(1429891635.019:593): avc:  denied  { nlmsg_relay } for  pid=1239 comm="sshd" scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=root:staff_r:staff_t:s0-s0:c0.c1023 tclass=netlink_audit_socket
926:type=AVC msg=audit(1429891635.019:593): avc:  denied  { audit_write } for  pid=1239 comm="sshd" capability=29  scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=root:staff_r:staff_t:s0-s0:c0.c1023 tclass=capability
927:type=USER_LOGIN msg=audit(1429891635.019:594): pid=1239 uid=0 auid=0 ses=1 subj=root:staff_r:staff_t:s0-s0:c0.c1023 msg='op=login id=0 exe="/usr/sbin/sshd" hostname=10.1.6.214 addr=10.1.6.214 terminal=ssh res=success'
928:type=SYSCALL msg=audit(1429891635.019:593): arch=c000003e syscall=44 success=yes exit=112 a0=8 a1=7fffb53cf070 a2=70 a3=0 items=0 ppid=1235 pid=1239 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1 comm="sshd" exe="/usr/sbin/sshd" subj=r
oot:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
929:type=AVC msg=audit(1429891635.019:595): avc:  denied  { read } for  pid=1239 comm="sshd" scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=root:staff_r:staff_t:s0-s0:c0.c1023 tclass=netlink_audit_socket
930:type=SYSCALL msg=audit(1429891635.019:595): arch=c000003e syscall=45 success=yes exit=36 a0=8 a1=7fffb53d13a0 a2=231c a3=42 items=0 ppid=1235 pid=1239 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1 comm="sshd" exe="/usr/sbin/sshd" subj=root:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
931:type=USER_START msg=audit(1429891635.019:596): pid=1239 uid=0 auid=0 ses=1 subj=root:staff_r:staff_t:s0-s0:c0.c1023 msg='op=login id=0 exe="/usr/sbin/sshd" hostname=10.1.6.214 addr=10.1.6.214 terminal=ssh res=success'
932:type=AVC msg=audit(1429891635.020:597): avc:  denied  { getopt } for  pid=1239 comm="sshd" laddr=10.1.12.168 lport=22 faddr=10.1.6.214 fport=36566 scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tclass=tcp_socket
933:type=SYSCALL msg=audit(1429891635.020:597): arch=c000003e syscall=55 success=yes exit=0 a0=3 a1=6 a2=1 a3=7fffb53d5b10 items=0 ppid=1235 pid=1239 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1 comm="sshd" exe="/usr/sbin/sshd" subj=root:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
934:type=AVC msg=audit(1429891635.020:598): avc:  denied  { setopt } for  pid=1239 comm="sshd" laddr=10.1.12.168 lport=22 faddr=10.1.6.214 fport=36566 scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tclass=tcp_socket
935:type=SYSCALL msg=audit(1429891635.020:598): arch=c000003e syscall=54 success=yes exit=0 a0=3 a1=6 a2=1 a3=7fffb53d5b10 items=0 ppid=1235 pid=1239 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1 comm="sshd" exe="/usr/sbin/sshd" subj=root:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
936:type=AVC msg=audit(1429891635.020:599): avc:  denied  { getattr } for  pid=1239 comm="sshd" laddr=10.1.12.168 lport=22 faddr=10.1.6.214 fport=36566 scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tclass=tcp_socket
937:type=SYSCALL msg=audit(1429891635.020:599): arch=c000003e syscall=51 success=yes exit=0 a0=3 a1=7fffb53d5b50 a2=7fffb53d5b4c a3=7fffb53d5b10 items=0 ppid=1235 pid=1239 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1 comm="sshd" exe="/usr/sbin/sshd" subj=root:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
938:type=CRYPTO_KEY_USER msg=audit(1429891635.020:600): pid=1243 uid=0 auid=0 ses=1 subj=root:staff_r:staff_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=df:92:3f:47:a0:92:83:a2:d0:fa:77:fc:78:a6:73:56 direction=? spid=1243 suid=0  exe="/usr/sbin/sshd" hostname=? addr=10.1.6.214 terminal=? res=success'
939:type=CRYPTO_KEY_USER msg=audit(1429891635.020:601): pid=1243 uid=0 auid=0 ses=1 subj=root:staff_r:staff_t:s0-s0:c0.c1023 msg='op=destroy kind=server fp=f1:c7:96:fe:c5:a9:3e:67:16:c2:dc:f9:4b:9d:bc:6f direction=? spid=1243 suid=0  exe="/usr/sbin/sshd" hostname=? addr=10.1.6.214 terminal=? res=success'
940:type=CRED_REFR msg=audit(1429891635.022:602): pid=1243 uid=0 auid=0 ses=1 subj=root:staff_r:staff_t:s0-s0:c0.c1023 msg='op=PAM:setcred acct="root" exe="/usr/sbin/sshd" hostname=10.1.6.214 addr=10.1.6.214 terminal=ssh res=success'
941:type=AVC msg=audit(1429891635.022:603): avc:  denied  { setuid } for  pid=1243 comm="sshd" capability=7  scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=root:staff_r:staff_t:s0-s0:c0.c1023 tclass=capability
942:type=SYSCALL msg=audit(1429891635.022:603): arch=c000003e syscall=117 success=yes exit=0 a0=0 a1=0 a2=0 a3=7f28ef5752e0 items=0 ppid=1239 pid=1243 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1 comm="sshd" exe="/usr/sbin/sshd" subj=root:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
943:type=AVC msg=audit(1429891635.022:604): avc:  denied  { setcurrent } for  pid=1243 comm="sshd" scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=root:staff_r:staff_t:s0-s0:c0.c1023 tclass=process
944:type=SYSCALL msg=audit(1429891635.022:604): arch=c000003e syscall=1 success=yes exit=36 a0=4 a1=7f28f4369c20 a2=24 a3=31632e30633a3073 items=0 ppid=1239 pid=1243 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1 comm="sshd" exe="/usr/sbin/sshd" subj=root:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
945:type=AVC msg=audit(1429891635.114:605): avc:  denied  { search } for  pid=1243 comm="rsync" name="/" dev="dm-5" ino=2 scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:object_r:auditd_log_t:s0 tclass=dir
946:type=SYSCALL msg=audit(1429891635.114:605): arch=c000003e syscall=80 success=yes exit=0 a0=7fdffb2e7510 a1=0 a2=e a3=676f6c2f7261762f items=0 ppid=1239 pid=1243 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1 comm="rsync" exe="/usr/bin/rsync" subj=root:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
947:type=AVC msg=audit(1429891635.114:606): avc:  denied  { getattr } for  pid=1243 comm="rsync" path="/var/log/audit/audit.log" dev="dm-5" ino=12 scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:object_r:auditd_log_t:s0 tclass=file
948:type=SYSCALL msg=audit(1429891635.114:606): arch=c000003e syscall=6 success=yes exit=0 a0=7fff3fd2e960 a1=7fff3fd2e8d0 a2=7fff3fd2e8d0 a3=0 items=0 ppid=1239 pid=1243 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1 comm="rsync" exe="/usr/bin/rsync" subj=root:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
949:type=AVC msg=audit(1429891635.116:607): avc:  denied  { read } for  pid=1243 comm="rsync" name="audit.log" dev="dm-5" ino=12 scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:object_r:auditd_log_t:s0 tclass=file
950:type=AVC msg=audit(1429891635.116:607): avc:  denied  { open } for  pid=1243 comm="rsync" path="/var/log/audit/audit.log" dev="dm-5" ino=12 scontext=root:staff_r:staff_t:s0-s0:c0.c1023 tcontext=system_u:object_r:auditd_log_t:s0 tclass=file
951:type=SYSCALL msg=audit(1429891635.116:607): arch=c000003e syscall=2 success=yes exit=3 a0=7fff3fd2d960 a1=0 a2=0 a3=0 items=0 ppid=1239 pid=1243 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=1 comm="rsync" exe="/usr/bin/rsync" subj=root:staff_r:staff_t:s0-s0:c0.c1023 key=(null)
</pre>

**Comment by mpalmi** [comment]
Per @pebenito's feedback, I'm going to close this out.

**Comment by minapoli** [comment]
Verified that staff_t denials are no longer generated on boot
