### ISSUE TITLE
Resolve ssh[d]_keygen_t denials

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#135]
In order to get this system booting in Enforcing, we will need to resolve the remaining kernel_t denials.

Assumptions:
- Work will be done off of mpalmi/clip@95bafa004072cff0cfef3bf12e7357e0f1ad998b
- Allow rules are needed to get CLIP booting in Enforcing
- Least privilege access model will be employed
- refpolicy guidelines for policy [development](https://github.com/TresysTechnology/refpolicy/wiki/Documentation) will be followed.

Subtasks:
- [x] Determine whether or not we want to support sshd_keygen
- [ ] Ensure all files are properly labeled
- [ ] Allow access to init unix_stream_sockets
- [ ] Allow sshd_keygen to access its sshd_key files
- [ ] Allow sshd_kegen access when restarting sshd with systecmtl. Issue #192 

----

audit2allow
<pre>
#============= sshd_keygen_t ==============
allow sshd_keygen_t init_t:unix_stream_socket getattr;
allow sshd_keygen_t shell_exec_t:file read;
allow sshd_keygen_t sshd_key_t:file getattr;
</pre>

audit.log
<pre>
878:type=AVC msg=audit(1429891549.504:564): avc:  denied  { read } for  pid=1233 comm="sshd-keygen" path="/usr/bin/bash" dev="dm-1" ino=263922 scontext=system_u:system_r:sshd_keygen_t:s0 tcontext=system_u:object_r:shell_exec_t:s0 tclass=file
879:type=SYSCALL msg=audit(1429891549.504:564): arch=c000003e syscall=10 success=yes exit=0 a0=6dc000 a1=1000 a2=1 a3=0 items=0 ppid=1 pid=1233 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="sshd-keygen" exe="/usr/bin/bash" subj=system_u:system_r:sshd_keygen_t:s0 key=(null)
880:type=AVC msg=audit(1429891549.506:565): avc:  denied  { getattr } for  pid=1233 comm="sshd-keygen" path="socket:[14870]" dev="sockfs" ino=14870 scontext=system_u:system_r:sshd_keygen_t:s0 tcontext=system_u:system_r:init_t:s0 tclass=unix_stream_socket
881:type=SYSCALL msg=audit(1429891549.506:565): arch=c000003e syscall=4 success=yes exit=0 a0=16de8b0 a1=7fffdb1983c0 a2=7fffdb1983c0 a3=7fffdb198170 items=0 ppid=1 pid=1233 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="sshd-keygen" exe="/usr/bin/bash" subj=system_u:system_r:sshd_keygen_t:s0 key=(null)
882:type=AVC msg=audit(1429891549.513:566): avc:  denied  { getattr } for  pid=1233 comm="sshd-keygen" path="/etc/ssh/ssh_host_rsa_key" dev="dm-1" ino=6800 scontext=system_u:system_r:sshd_keygen_t:s0 tcontext=system_u:object_r:sshd_key_t:s0 tclass=file
883:type=SYSCALL msg=audit(1429891549.513:566): arch=c000003e syscall=4 success=yes exit=0 a0=1709190 a1=7fffdb198430 a2=7fffdb198430 a3=8 items=0 ppid=1 pid=1233 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="sshd-keygen" exe="/usr/bin/bash" subj=system_u:system_r:sshd_keygen_t:s0 key=(null)
</pre>

**Comment by mpalmi** [comment]
This is where the ssh_keygen_t policy stands:

>#============= ssh_keygen_t ==============
allow ssh_keygen_t cert_t:file { read getattr open };

<pre>
type=AVC msg=audit(1437581224.380:410): avc:  denied  { read } for  pid=1230 comm="ssh-keygen" name="openssl.cnf" dev="dm-1" ino=4408 scontext=system_u:system_r:ssh_keygen_t:s0 tcontext=system_u:object_r:cert_t:s0 tclass=file
type=AVC msg=audit(1437581224.380:410): avc:  denied  { open } for  pid=1230 comm="ssh-keygen" path="/etc/pki/tls/openssl.cnf" dev="dm-1" ino=4408 scontext=system_u:system_r:ssh_keygen_t:s0 tcontext=system_u:object_r:cert_t:s0 tclass=file
type=AVC msg=audit(1437581224.380:411): avc:  denied  { getattr } for  pid=1230 comm="ssh-keygen" path="/etc/pki/tls/openssl.cnf" dev="dm-1" ino=4408 scontext=system_u:system_r:ssh_keygen_t:s0 tcontext=system_u:object_r:cert_t:s0 tclass=file
</pre>

**Comment by ykhodorkovskiy** [comment]
@mpalmi ssh* is removed in production, therefore no policy needs to be written for this.
