### ISSUE TITLE
GettingStarted link is dead on DownloadReleaseEL5 page

### ISSUE THREAD

**Issue by minapoli** [TresysTechnology/clip#138]
The GettingStarted link under the Dependencies section on https://github.com/TresysTechnology/clip/wiki/DownloadReleaseEL5 is dead. 

It tries to get to https://github.com/projects/clip/wiki/GettingStarted#RHEL5.4 which doesnt exist.

**Comment by mpalmi** [comment]
It may be appropriate for that link to point to either of the following locations:
* https://github.com/TresysTechnology/clip/wiki/GettingStarted
* https://github.com/TresysTechnology/clip/wiki/GettingStarted#installing-the-clip-313-rhel-54-or-clip-314-rhel-55-base-system

**Comment by ykhodorkovskiy** [comment]
Also, update any stale STIG content with instructions to contact Tresys.

**Comment by ykhodorkovskiy** [comment]
Updated README.md and https://github.com/TresysTechnology/clip/wiki/AnalysisBackground

**Comment by minapoli** [comment]
testing
