### ISSUE TITLE
TAR_DEPS in clip-selinux-policy/Makefile needs more granular file list

### ISSUE THREAD

**Issue by ykhodorkovskiy** [TresysTechnology/clip#148]
We should only detect changes in *.te, *.fc, *.if, policy.conf and other files that I am probably missing.

**Comment by mpalmi** [comment]
Actually, I think we should be okay as-is.
I believe the extra files are only generated when you run `make` in the packages/clip-selinux-policy/clip-selinux-policy/ directory, which you really shouldn't be doing anyway. I will verify so that we're 100% certain before closing this out.

**Comment by ykhodorkovskiy** [comment]
@mpalmi Did you have a chance to verify this?

**Comment by mpalmi** [comment]
Verified that these files are only left in the directory when a `make` is called from packages/clip-selinunx-policy/clip-selinux-policy/.
