### ISSUE TITLE
Resolve systemd_tmpfiles_t denials

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#150]
In order to get this system booting in Enforcing, we will need to resolve the remaining kernel_t denials.

Assumptions:
- Work will be done off of mpalmi/clip@95bafa004072cff0cfef3bf12e7357e0f1ad998b
- Allow rules are needed to get CLIP booting in Enforcing
- Least privilege access model will be employed
- refpolicy guidelines for policy [development](https://github.com/TresysTechnology/refpolicy/wiki/Documentation) will be followed.

Subtasks:
- [x] Ensure all files are properly labeled
- [x] Determine security implications of allowing denials
- [x] Write appropriate policy

----

audit2allow
<pre>
#============= systemd_tmpfiles_t ==============
allow systemd_tmpfiles_t fuse_device_t:chr_file { create getattr };
allow systemd_tmpfiles_t self:capability mknod;  
</pre>

audit.log
<pre>
type=AVC msg=audit(1431434414.680:55): avc:  denied  { mknod } for  pid=431 comm="systemd-tmpfile" capability=27  scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:system_r:systemd_tmpfiles_t:s0 tclass=capability  

type=AVC msg=audit(1431434414.680:55): avc:  denied  { create } for  pid=431 comm="systemd-tmpfile" name="fuse" scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:fuse_device_t:s0 tclass=chr_file

type=AVC msg=audit(1431434394.523:53): avc:  denied  { mknod } for  pid=423 comm="systemd-tmpfile" capability=27  scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:system_r:systemd_tmpfiles_t:s0 tclass=capability

type=AVC msg=audit(1431434394.523:53): avc:  denied  { create } for  pid=423 comm="systemd-tmpfile" name="fuse" scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:fuse_device_t:s0 tclass=chr_file

type=AVC msg=audit(1431434394.523:54): avc:  denied  { getattr } for  pid=423 comm="systemd-tmpfile" path="/dev/fuse" dev="devtmpfs" ino=9742 scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:fuse_device_t:s0 tclass=chr_file

type=AVC msg=audit(1431434414.680:55): avc:  denied  { mknod } for  pid=431 comm="systemd-tmpfile" capability=27  scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:system_r:systemd_tmpfiles_t:s0 tclass=capability

type=AVC msg=audit(1431434394.523:53): avc:  denied  { mknod } for  pid=423 comm="systemd-tmpfile" capability=27  scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:system_r:systemd_tmpfiles_t:s0 tclass=capability

type=AVC msg=audit(1431435661.494:500): avc:  denied  { use } for  pid=1255 comm="crond" path="/run/systemd/sessions/1.ref" dev="tmpfs" ino=15279 scontext=system_u:system_r:crond_t:s0-s0:c0.c1023 tcontext=system_u:system_r:systemd_logind_t:s0 tclass=fd

type=AVC msg=audit(1431437383.113:560): avc:  denied  { use } for  pid=1327 comm="sshd" path="/run/systemd/sessions/3.ref" dev="tmpfs" ino=15729 scontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:system_r:systemd_logind_t:s0 tclass=fd

</pre>

**Comment by mpalmi** [comment]
No denials seen for systemd_tmpfiles.
@tomhurd Could you please review https://github.com/mpalmi/clip/commit/18342f2b4f22c186f9da1744209224805650e10d

**Comment by ykhodorkovskiy** [comment]
```
type=AVC msg=audit(1432668981.614:536): avc:  denied  { getattr } for  pid=1695 comm="systemd-tmpfile" path="/tmp/ssh-3kp9QE5EZM/agent.1555" dev="dm-4" ino=22 scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=toor_u:object_r:user_tmp_t:s0 tclass=sock_file
type=AVC msg=audit(1432668981.614:537): avc:  denied  { read } for  pid=1695 comm="systemd-tmpfile" name="unix" dev="proc" ino=4026532002 scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:proc_net_t:s0 tclass=file
type=AVC msg=audit(1432668981.614:537): avc:  denied  { open } for  pid=1695 comm="systemd-tmpfile" path="/proc/1695/net/unix" dev="proc" ino=4026532002 scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:proc_net_t:s0 tclass=file
type=AVC msg=audit(1432668981.614:538): avc:  denied  { getattr } for  pid=1695 comm="systemd-tmpfile" path="/proc/1695/net/unix" dev="proc" ino=4026532002 scontext=system_u:system_r:systemd_tmpfiles_t:s0 tcontext=system_u:object_r:proc_net_t:s0 tclass=file
#============= systemd_tmpfiles_t ==============
allow systemd_tmpfiles_t proc_net_t:file { read getattr open };
allow systemd_tmpfiles_t user_tmp_t:sock_file getattr;
```

**Comment by doverride** [comment]
allow systemd_tmpfiles_t user_tmp_t:sock_file getattr;

systemd_tmpfiles needs to be able to maintain all of /tmp. It serves, amongst other things, as an replacement to tmpreaper.

**Comment by ykhodorkovskiy** [comment]
These denials have been solved in another commit by @mpalmi

**Comment by ykhodorkovskiy** [comment]
@mpalmi says he wants to take a second look at this

**Comment by ykhodorkovskiy** [comment]
@mpalmi can you please update this issue with what needs to be done, if this is not finished?

**Comment by mpalmi** [comment]
The only remaining denials I see are dontaudited. I'm going to go ahead and close this out.
