### ISSUE TITLE
aide cron job fails to run

### ISSUE THREAD

**Issue by minapoli** [TresysTechnology/clip#152]
It looks like there needs to be a user specified before the aide command in /etc/crontab for the command to run.

**Comment by minapoli** [comment]
The error message that is generated in /var/log/cron also states
((null)) No security context but SELinux in permissive mode, continuing (/etc/crontab)
This might indicate that it needs another parameter to work in enforcing.

**Comment by mpalmi** [comment]
In the meantime, I propose we add another flag to toggle AIDE.
This may prove useful if someone does not want to use this aide feature.
Patch incoming...

**Comment by minapoli** [comment]
CONFIG_BUILD_AIDE evaluation in the kickstart file is missing the $

**Comment by mpalmi** [comment]
Submitted pull request: https://github.com/TresysTechnology/clip/pull/165

**Comment by minapoli** [comment]
CONFIG_BUILD_AIDE should probably be added to CONFIG_BUILD_BASH_VARS as well

**Comment by minapoli** [comment]
and add it to export at the bottom of CONFIG_BUILD

**Comment by ykhodorkovskiy** [comment]
Verified that there are no lvm denials.
