### ISSUE TITLE
Resolve audisp_t denials

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#158]
In order to get this system booting in Enforcing, we will need to resolve the remaining kernel_t denials.

Assumptions:
- Work will be done off of mpalmi/clip@95bafa004072cff0cfef3bf12e7357e0f1ad998b
- Allow rules are needed to get CLIP booting in Enforcing
- Least privilege access model will be employed
- refpolicy guidelines for policy [development](https://github.com/TresysTechnology/refpolicy/wiki/Documentation) will be followed.

Subtasks:
- [x] Allow audisp to send to kernel dgram sockets

----

audit2allow
<pre>
#============= audisp_t ==============
allow audisp_t kernel_t:unix_dgram_socket sendto;
</pre>

audit.log
<pre>
type=AVC msg=audit(1432137219.902:125): avc:  denied  { sendto } for  pid=573 comm="audispd" path="/dev/log" scontext=system_u:system_r:audisp_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=unix_dgram_socket
</pre>

**Comment by ykhodorkovskiy** [comment]
Verified there are no audisp denials
