### ISSUE TITLE
Investigate whether or not we want sysfs/debugfs labeling

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#159]
Stephen Smalley recently submitted patches for debugfs/sysfs labeling through genfscon:

http://marc.info/?l=selinux&m=143214050004174&w=2
http://marc.info/?l=selinux&m=143206500715011&w=2

We may want to consider pulling these into CLIP to give us better coverage w/r/t file-labeling.

**Comment by pebenito** [comment]
This cannot be used as it requires kernel changes.
