### ISSUE TITLE
Resolve shutdown_t denials

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#164]
In order to get this system booting in Enforcing, we will need to resolve the remaining kernel_t denials.

Assumptions:
- Work will be done off of mpalmi/clip@95bafa004072cff0cfef3bf12e7357e0f1ad998b
- Allow rules are needed to get CLIP booting in Enforcing
- Least privilege access model will be employed
- refpolicy guidelines for policy [development](https://github.com/TresysTechnology/refpolicy/wiki/Documentation) will be followed.

Subtasks:
- [ ] Ensure all files are properly labeled
- [ ] Resolve shutdown denials

----

>#============= shutdown_t ==============
allow shutdown_t kernel_t:dir search;
allow shutdown_t kernel_t:fd use;
allow shutdown_t self:capability ipc_lock;

<pre>
type=AVC msg=audit(1432312882.237:93): avc:  denied  { use } for  pid=1 comm="systemd-shutdow" path="/dev/null" dev="devtmpfs" ino=4483 scontext=system_u:system_r:shutdown_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=fd
type=AVC msg=audit(1432312882.237:94): avc:  denied  { ipc_lock } for  pid=1 comm="systemd-shutdow" capability=14  scontext=system_u:system_r:shutdown_t:s0 tcontext=system_u:system_r:shutdown_t:s0 tclass=capability
type=AVC msg=audit(1432312882.240:95): avc:  denied  { search } for  pid=1 comm="systemd-shutdow" name="2" dev="proc" ino=8387 scontext=system_u:system_r:shutdown_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=dir
</pre>

**Comment by mpalmi** [comment]
Still getting the following denials:

>#============= shutdown_t ==============
allow shutdown_t kernel_t:fd use;
allow shutdown_t kernel_t:file read;

<pre>
type=AVC msg=audit(1433422865.071:90): avc:  denied  { use } for  pid=1 comm="systemd-shutdow" path="/dev/null" dev="devtmpfs" ino=4483 scontext=system_u:system_r:shutdown_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=fd
type=AVC msg=audit(1433422865.074:91): avc:  denied  { read } for  pid=1 comm="systemd-shutdow" name="status" dev="proc" ino=8412 scontext=system_u:system_r:shutdown_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=file
</pre>

**Comment by mpalmi** [comment]
><b>mpalmi</b> commented 6 days ago

>Still getting the following denials:

>#============= shutdown_t ==============
allow shutdown_t kernel_t:fd use;
allow shutdown_t kernel_t:file read;

>
type=AVC msg=audit(1433422865.071:90): avc:  denied  { use } for  pid=1 comm="systemd-shutdow" path="/dev/null" dev="devtmpfs" ino=4483 scontext=system_u:system_r:shutdown_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=fd
type=AVC msg=audit(1433422865.074:91): avc:  denied  { read } for  pid=1 comm="systemd-shutdow" name="status" dev="proc" ino=8412 scontext=system_u:system_r:shutdown_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=file

I'm assuming that the kernel_t fd denial is due to a leaked file descriptor, as /dev/null is not labeled kernel_t.
<pre>
[root@localhost ~]# ls -li /dev/null && ls -lZ /dev/null
4483 crw-rw-rw-. 1 root root 1, 3 Jun 10 17:37 /dev/null
crw-rw-rw-. root root system_u:object_r:null_device_t:s0 /dev/null
</pre>

@pebenito @doverride @tomhurd Thoughts?

**Comment by mpalmi** [comment]
Ah, I was thinking about this incorrectly. The label of the fd corresponds with the domain that created the fd, and not the label of the file.

**Comment by ykhodorkovskiy** [comment]
There are a few more denials that are related:

```type=AVC msg=audit(1436288632.851:89): avc:  denied  { open } for  pid=1 comm="systemd-shutdow" path="/proc/2/status" dev="proc" ino=9393 scontext=system_u:system_r:shutdown_t:s0 tcontext=system_u:system_r:kernel_t:s0 tclass=file
type=USER_AVC msg=audit(1436288718.848:481): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='avc:  denied  { start } for auid=1000 uid=0 gid=0 path="/usr/lib/systemd/system/poweroff.target" cmdline="shutdown -h now" scontext=toor_u:toor_r:toor_t:s0 tcontext=system_u:object_r:power_unit_file_t:s0 tclass=service  exe="/usr/lib/systemd/systemd" sauid=0 hostname=? addr=? terminal=?'
type=AVC msg=audit(1436288719.839:504): avc:  denied  { unlink } for  pid=1661 comm="rm" name=".need_shutdown" dev="tmpfs" ino=8238 scontext=system_u:system_r:initrc_t:s0 tcontext=system_u:object_r:tmpfs_t:s0 tclass=file
```

**Comment by ykhodorkovskiy** [comment]
Now I am seeing an lvm_t denial

```
type=AVC msg=audit(1436371192.480:89): avc:  denied  { search } for  pid=1 comm="systemd-shutdow" name="634" dev="proc" ino=11113 scontext=system_u:system_r:shutdown_t:s0 tcontext=system_u:system_r:lvm_t:s0 tclass=dir
```

**Comment by doverride** [comment]
On Wed, Jul 08, 2015 at 09:52:16AM -0700, Yuli Khodorkovskiy wrote:
> Now I am seeing an lvm_t denial
> 
> ```
> type=AVC msg=audit(1436371192.480:89): avc:  denied  { search } for  pid=1 comm="systemd-shutdow" name="634" dev="proc" ino=11113 scontext=system_u:system_r:shutdown_t:s0 tcontext=system_u:system_r:lvm_t:s0 tclass=dir
> ```
> 

Yes systemd-shutdown needs to be able to read all domains state (shutdown becomes pid1 when you shutdown/reboot)

see: https://github.com/doverride/laptop/blob/master/sources/modules/contrib/system/systemd/shutdown.cil

> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/TresysTechnology/clip/issues/164#issuecomment-119657014

-- 
02DFF788
4D30 903A 1CF3 B756 FB48  1514 3148 83A2 02DF F788
http://keys.gnupg.net/pks/lookup?op=vindex&search=0x314883A202DFF788
Dominick Grift
