### ISSUE TITLE
Request for unknown module key 

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#168]
The following error message `Request for unknown module key 'Red Hat Enterprise Linux kernel signing key: 00aa5f56c587bd82f2f99d64ba83dd1e9e0d334a' err -13` seen on first boot in Enforcing.
![2015-05-27-180513_1920x1080_scrot](https://cloud.githubusercontent.com/assets/7817675/7848687/054135b6-049c-11e5-9f15-9b0e1c7f4727.png)

**Comment by ykhodorkovskiy** [comment]
@mpalmi This looks like a problem in the upstream kernel [1] because the hardware clock isn't set.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=921300

**Comment by ykhodorkovskiy** [comment]
This was fixed in 9bb181ebff386f1eb15d52f30a28c0cd03259fcb
