### ISSUE TITLE
There's no way to perform a shutdown or reboot on an enforcing production system

### ISSUE THREAD

**Issue by minapoli** [TresysTechnology/clip#169]
Sudo is prevented on an enforcing production system.  Because of this, shutdown and reboot will not work.
There should be a method for performing these operations.

**Comment by mpalmi** [comment]
I believe this should be cleared up when we pull in https://github.com/TresysTechnology/clip/commit/6f298b80bcdfc6e3b14d197631537c227d473566. Will want to verify after working on the cherry-pick.

**Comment by ykhodorkovskiy** [comment]
Assigning this to you per our discussion today. Please close this and open a new bug as appropriate.

**Comment by mpalmi** [comment]
@ykhodorkovskiy This gets us rebooting/shutting down in Enforcing. (rebased on master)

**Comment by mpalmi** [comment]
@ykhodorkovskiy Okay, fixed and tested on an Enforcing build.

**Comment by mpalmi** [comment]
Apparently this still does not fix the shutdown issue. I was testing with a non-production build, so the UNCONFINED_TOOR variable was set to 'y.' I'm going to try setting that to 'n' for a debug build and see if that produces denials in Permissive.

**Comment by mpalmi** [comment]
> <b>mpalmi</b> commented 18 hours ago
Apparently this still does not fix the shutdown issue. I was testing with a non-production build, so the UNCONFINED_TOOR variable was set to 'y.' I'm going to try setting that to 'n' for a debug build and see if that produces denials in Permissive.

This was, in fact, the issue. Another patch coming shortly, tested with UNCONFINED_TOOR=n

**Comment by mpalmi** [comment]
Tested with a clean tree. UNCONFINED_TOOR=n in Enforcing.
