### ISSUE TITLE
/run/faillock has wrong label

### ISSUE THREAD

**Issue by tomhurd** [TresysTechnology/clip#175]
/run/faillock is labeled as var_run_t, but matchpathcon says it should be faillog_t

Sounds like whatever is creating it doesn't have the correct filetrans.

**Comment by mpalmi** [comment]
![2015-06-10-111023_5760x1080_scrot](https://cloud.githubusercontent.com/assets/7817675/8086056/726ae78e-0f61-11e5-9f8d-f1cb2cd9c292.png)

It looks like this file has the right label on my box.
@tomhurd Can you give a bit more information about when/how this was appearing? 
Enforcing/Permissive, commit #, etc.

**Comment by ykhodorkovskiy** [comment]
I built master in enforcing and the following changes to CONFIG_BUILD and faillock is labeled with var_run_t

```
-CONFIG_BUILD_PRODUCTION := n
+CONFIG_BUILD_PRODUCTION := y
 ifeq ($(CONFIG_BUILD_PRODUCTION),y)
   CONFIG_BUILD_ENFORCING_MODE := y
-  CONFIG_BUILD_UNCONFINED_TOOR := n
+  CONFIG_BUILD_UNCONFINED_TOOR := y
   CONFIG_BUILD_AIDE := y
   ENABLE_NETWORKING := n
 else
```

**Comment by pebenito** [comment]
If you have to make those changes; i.e. make toor unconfined in production, that isn't a certifiable system, so we shouldn't care about that configuration.

**Comment by ykhodorkovskiy** [comment]
I verified that this occurs in a production system without unconfined toor as well.

**Comment by mpalmi** [comment]
This only happening in Enforcing, regardless of the value of `CONFIG_BUILD_UNCONFINED_TOOR`. I'm trying to track down the issue.
Here are the denials for `tcontext=system_u:object_r:faillog_t:s0`:
<pre>
type=AVC msg=audit(1434990261.760:451): avc:  denied  { read write } for  pid=1263 comm="sudo" name="toor" dev="tmpfs" ino=15214 scontext=toor_u:staff_r:staff_t:s0 tcontext=system_u:object_r:faillog_t:s0 tclass=file
type=AVC msg=audit(1434990261.760:451): avc:  denied  { open } for  pid=1263 comm="sudo" path="/run/faillock/toor" dev="tmpfs" ino=15214 scontext=toor_u:staff_r:staff_t:s0 tcontext=system_u:object_r:faillog_t:s0 tclass=file
type=AVC msg=audit(1434990261.760:452): avc:  denied  { lock } for  pid=1263 comm="sudo" path="/run/faillock/toor" dev="tmpfs" ino=15214 scontext=toor_u:staff_r:staff_t:s0 tcontext=system_u:object_r:faillog_t:s0 tclass=file
type=AVC msg=audit(1434990714.016:481): avc:  denied  { search } for  pid=1284 comm="sshd" name="faillock" dev="tmpfs" ino=12427 scontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:faillog_t:s0 tclass=dir
type=AVC msg=audit(1434990714.022:483): avc:  denied  { search } for  pid=1284 comm="sshd" name="faillock" dev="tmpfs" ino=12427 scontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:faillog_t:s0 tclass=dir
type=AVC msg=audit(1434990714.022:484): avc:  denied  { write } for  pid=1284 comm="sshd" name="faillock" dev="tmpfs" ino=12427 scontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:faillog_t:s0 tclass=dir
type=AVC msg=audit(1434990714.022:484): avc:  denied  { add_name } for  pid=1284 comm="sshd" name="root" scontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:faillog_t:s0 tclass=dir
type=AVC msg=audit(1434990714.022:484): avc:  denied  { create } for  pid=1284 comm="sshd" name="root" scontext=system_u:system_r:sshd_t:s0-s0:c0.c1023 tcontext=system_u:object_r:faillog_t:s0 tclass=file
</pre>

**Comment by mpalmi** [comment]
We need to figure out which process is creating this file and then add the appropriate transition so that the file gets the correct label in Enforcing.

I believe this file is being created by init, which the appropriate transition, so I'm not really sure why this is still being mislabeled. Need to investigate further.

**Comment by minapoli** [comment]
This issue was due to systemd-tmpfiles using fscreate to set the label. The seutil_libselinux_linked interface needed to be called for systemd_tmpfiles_t so that it could use libselinux correctly.
