### ISSUE TITLE
systemd service control policy

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#184]
Write policy for starting and stopping critical system services.
This will involve adding/modifying the current systemd interfaces, adding/modifying the "service" access vector, and fixing/adding calls to these interfaces in the proper domains, etc.

**Comment by pebenito** [comment]
Not clear what you mean by "adding/modifying" the service object class, but that would mean changing systemd enforcement (i.e. code changes), which isn't an option.

**Comment by mpalmi** [comment]
><b>pebenito</b> commented a minute ago
Not clear what you mean by "adding/modifying" the service object class, but that would mean changing systemd enforcement (i.e. code changes), which isn't an option.

see: https://github.com/mpalmi/clip/commit/32942af51ed62fb5e9d3c534ef6545094a0dc3f5#diff-8ed96fe97303ba00838aefe544ad93ccR335

**Comment by mpalmi** [comment]
Duplicate #190 is a more precise/accurate description of the issue.
