### ISSUE TITLE
Let init write kmsg

### ISSUE THREAD

**Issue by mpalmi** [TresysTechnology/clip#189]
>allow init_t event_device_t:chr_file { write open };

<pre>
149:type=AVC msg=audit(1438269572.482:37): avc:  denied  { write } for  pid=1 comm="systemd" name="kmsg" dev="devtmpfs" ino=4489 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:event_device_t:s0 tclass=chr_file
150:type=AVC msg=audit(1438269572.482:38): avc:  denied  { open } for  pid=1 comm="systemd" path="/dev/kmsg" dev="devtmpfs" ino=4489 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:event_device_t:s0 tclass=chr_file
77:type=AVC msg=audit(1438269556.466:37): avc:  denied  { write } for  pid=1 comm="systemd" name="kmsg" dev="devtmpfs" ino=4489 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:event_device_t:s0 tclass=chr_file
78:type=AVC msg=audit(1438269556.466:38): avc:  denied  { open } for  pid=1 comm="systemd" path="/dev/kmsg" dev="devtmpfs" ino=4489 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:event_device_t:s0 tclass=chr_file
149:type=AVC msg=audit(1438269572.482:37): avc:  denied  { write } for  pid=1 comm="systemd" name="kmsg" dev="devtmpfs" ino=4489 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:event_device_t:s0 tclass=chr_file
150:type=AVC msg=audit(1438269572.482:38): avc:  denied  { open } for  pid=1 comm="systemd" path="/dev/kmsg" dev="devtmpfs" ino=4489 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:event_device_t:s0 tclass=chr_file
77:type=AVC msg=audit(1438269556.466:37): avc:  denied  { write } for  pid=1 comm="systemd" name="kmsg" dev="devtmpfs" ino=4489 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:event_device_t:s0 tclass=chr_file
78:type=AVC msg=audit(1438269556.466:38): avc:  denied  { open } for  pid=1 comm="systemd" path="/dev/kmsg" dev="devtmpfs" ino=4489 scontext=system_u:system_r:init_t:s0 tcontext=system_u:object_r:event_device_t:s0 tclass=chr_file
</pre>

**Comment by mpalmi** [comment]
@ykhodorkovskiy Could you verify this please?

**Comment by ykhodorkovskiy** [comment]
ACK
