### ISSUE TITLE
Seeking help to write a support statement for CLIP

### ISSUE THREAD

**Issue by shawndwells** [TresysTechnology/clip#201]
Within Red Hat Public Sector, we've been getting a rise in customer questions regarding support for RHEL images configured with CLIP. I haven't been keeping track with CLIP for awhile and lost sight of what system components were modified by CLIP... so I wanted to ask here :)

In the past, CLIP has replaced some system components (like PAM) with hardened editions. These changes made complete sense, so Red Hat would tell customers that deploying CLIP was entirely fine -- but if you run into PAM issues, we may request you use the native PAM. 

Are there any RHEL components *replaced* by CLIP these days? If so, can you share pointers to what has changed?

The goal of this is for Red Hat to understand deltas between "native RHEL" and CLIP, in order to provide support statements to various customers. And if there are deficiencies in native RHEL, perhaps work together to create RFEs so replacement components are no longer needed.

**Comment by shawndwells** [comment]
p.s. custom SELinux policies are totally fine -- looking for system components, like the PAM example above

**Comment by mpalmi** [comment]
If I'm not mistaken, the only patches we currently carry are to the Lorax package.
Everything else should be in line with native RHEL.

**Comment by ykhodorkovskiy** [comment]
Hey @shawndwells,

Besides SELinux policy, we made a few modifications to version 0.1.20 of SSG. We are planning to pull in the latest version of SSG prior to our final release of CLIP for RHEL 7.0.

We also made changes to lorax, livecd-tools, and pungi, but these are mostly build system tweaks. You can find details of all the changes we made to redhat packages below:

* Lorax (forked from 19.6.45)
    * Remove the timeout from the bootloader. 0c45c16b34fab5385c2982d31ff86482b5aebec5
    * Created a cache directory for lorax. After a build, installroot will be copied to the cache directory. This will ensure that RPMs will not have to be reinstalled when rebuilding which is a large chunk of the build time. Build times are reduced from 10 mins to 4 mins on the Tresys build system. 6973219554111795901e9eb698c0c19a4339c5df
    * Patched code that removed build artifacts. If a file or directory do not exist, the build will not exit. 258c4fe514926e48e7cce31baac596474897fc3a and ca21c637110b1cd21c96d049ff201d380acdcdd7
    * Removed some packages rpm-ostree and kexec-tools-addon from the template file to remove some errors during a build. 7c0eeba3a48e4fbc786ed55f6dcb477550b44821
    * Fixed a bug with generate_module_data where "module-info" was causing problems. The file is now created if kver is a directory. 10e8ae6eda6
* Pungi (forked from 2.13)
    * Make pungi not use symlinks when generating an iso 86f13ce5a284051218e7ade2f008c44ed89591ba
    * Clear out the pungi log after each build 593cced99133d2c5660602f1ce3a381086e9e1c9
* SSG (forked from 0.1.20. Some of these patches such as the DoD login banner have been added in newer version of SSG which we will eventually update to)
    * Add login banner text when logging in to the stig-rhel7-server-upstream profile ff2a4a279cad9be23be6aae0e7e8e3b0a4549937
    * Dropped Jboss content since we don't use it on CLIP 27331d152bd499d02e469a15e9b047bb15921b27
* Livecd-tools (forked from 20.6)
    * Removed hfsplus tools requirement from the spec file 006d0692627d91ccce898100b1f3c7411aa81464
    * Patched imgcreate for CLIP 006d0692627d91ccce898100b1f3c7411aa81464
    * Modified kickstart.py to correct livecd arguments 006d0692627d91ccce898100b1f3c7411aa81464
