### ISSUE TITLE
Dracut modules missing on RHEL7 build

### ISSUE THREAD

**Issue by ghost** [TresysTechnology/clip#21]
in build.log:

rebuilding initramfs images
rebuilding boot/initramfs-3.10.0-123.el7.x86_64.img
No '/dev/log' or 'logger' included for syslog logging
dracut module 'anaconda' cannot be found or installed.
dracut module 'anaconda' cannot be found or installed.
cat: write error: Broken pipe
rebuilding boot/upgrade-3.10.0-123.el7.x86_64.img
No '/dev/log' or 'logger' included for syslog logging

**Comment by GitSoftwareNow** [comment]
me too 


dracut module 'anaconda' cannot be found or installed.
