### ISSUE TITLE
pull in the latest release of SSG prior to final release

### ISSUE THREAD

**Issue by ykhodorkovskiy** [TresysTechnology/clip#210]
See what the delta is between current SSG version in CLIP and upstream. Update our version if necessary.

**Comment by rprevette** [comment]
After looking into this, we found that RHN now provides openscap-1.2.5-3 and ssg-0.1.25-3.

As the SSG provided by RHN is currently the same version already in CLIP (0.1.25), we're leaving CLIP's packages' versions as they are for the RHEL_7_Final milestone. 

Moving forward, we'll remove these as 3rd party packages within CLIP and instead use the RHN provided packages.

I'm moving the milestone for this ticket to Future -- this ticket will instead be to track the work to shift to using the RHN packages.

**Comment by ykhodorkovskiy** [comment]
When removing the packages in future releases, make sure patches we provided to the upstream code are no longer needed, or add them as necessary.

**Comment by minapoli** [comment]
merged with pull request #235
