### ISSUE TITLE
check vulnerability list and patch failures

### ISSUE THREAD

**Issue by ykhodorkovskiy** [TresysTechnology/clip#215]
Red hat provides a list of vulnerabilities that can be passed to oscap.

```
$ wget http://www.redhat.com/security/data/oval/com.redhat.rhsa-all.xml
$ oscap oval eval --results rhsa-results-oval.xml --report oval-report.html com.redhat.rhsa-all.xml
```

Check and patch anything that could affect CLIP.

**Comment by minapoli** [comment]
I ran the latest (updated 20-Jan-2016) and there were no failures.

**Comment by ykhodorkovskiy** [comment]
It will be useful to run these checks with each point release of CLIP. Perhaps to help remember, as you close out the ticket for one milestone, open a new ticket for the next milestone?
