### ISSUE TITLE
Fix SSG audit failures

### ISSUE THREAD

**Issue by minapoli** [TresysTechnology/clip#222]
There are 4 failures after remediation that all have to do with auditing. At first glance, these all appear to be easily fixable so this should be done for RHEL_7_Final.

**Comment by minapoli** [comment]
Remediation of the audit rules currently does not work in this version of ssg. Future versions may fix this. We'll manually add the audit rules for now, but we should check that this is still necessary when we pull in later versions of ssg.

**Comment by rprevette** [comment]
There are no longer any failures after remediation, much less any for auditing.

This ticket will be closed.
