### ISSUE TITLE
Update the README.md to be consistent with what is supported in rhel 7

### ISSUE THREAD

**Issue by rprevette** [TresysTechnology/clip#223]
In the README.md file, we currently have a lot of outdated information about supporting LiveCDs.

As the README.md is versioned, the RHEL 7 release version should only state that we no longer support LiveCDs.  The rest should be removed for consistency through the document.

**Comment by minapoli** [comment]
References to rhel 5 and 6 should be removed and info should be added for rhel7 as needed
