### ISSUE TITLE
clip-rhel7 kickstart file -- logvol does't support both percent and size parameters.

### ISSUE THREAD

**Issue by rprevette** [TresysTechnology/clip#237]
After updating to a new version of pykicstart, we see the build system fail due to being unable to parse the kickstart file.

The error is for the line:
 logvol /home  --vgname=vg00  --name=home  --fstype=ext4  --size=1  --fsoptions=defaults,nosuid,nodev   --percent=10  --grow

Stating that "percent" and "grow" are mutually exclusive.   This matches the fedoraproject documentation  found here: 
https://docs.fedoraproject.org/en-US/Fedora/22/html/Installation_Guide/sect-kickstart-commands-logvol.html

I think we want to have our /home partition be of minsize  (--size= )  that grows,   or else be of min-percent ( --percent)  that grows.

**Comment by ykhodorkovskiy** [comment]
You can specify a specific version of an RPM to use in your pkglist.rhel file. This should save you from doing this work.

**Comment by minapoli** [comment]
Since the line in the kickstart file is wrong and the newer versions of pykickstart are actually fixing a bug that caused it to work anyway, I would prefer that we just fix the line. Try removing the --size=1 parameter and see if the overall size of the partition is effected. My hunch is that the bug was causing it to just use the second setting (--percent=10).

**Comment by rprevette** [comment]
I've tried both methods.

Using the --size ,  removing the --percent   causes the /home partition to go from being allocated 2.4G to being allocated 182M

Using the --percent, removing the --size  causes all partitions to stay relatively the same. 

Seems like we should remove the '--size' parameter, which seems to have little-to-no affect on the allocation sizes on the built system.

**Comment by minapoli** [comment]
This was merged in with pull request #238
