### ISSUE TITLE
Get SSG working in enforcing

### ISSUE THREAD

**Issue by ykhodorkovskiy** [TresysTechnology/clip#60]
This is dependent on the SSG actually being pulled into CLIP and having a valid profile we can use.

**Comment by ykhodorkovskiy** [comment]
@mpalmi please assign a time estimate label for this issue.

**Comment by mpalmi** [comment]
Pretty sure this already works. Just need to test/verify.

**Comment by mpalmi** [comment]
We're currently able to do remediation and scans on boot in Enforcing. This is all we're concerned with at the time.
