### ISSUE TITLE
Changes to corenetwork.if.in do not take effect

### ISSUE THREAD

**Issue by ykhodorkovskiy** [TresysTechnology/clip#75]
I needed to add some interfaces to corenetwork, but the changes did not get included in the rpm until I deleted corenetwork.if from the repository.

**Comment by ykhodorkovskiy** [comment]
@mpalmi please assign a time estimate label for this issue.

**Comment by mpalmi** [comment]
Verify that this functionality is expected. I usually `make bare` before doing a policy build. Perhaps we want to support delta builds though.

**Comment by mpalmi** [comment]
Per @pebenito's feedback, I'm going to close this out
