### ISSUE TITLE
Write wiki/help.txt for failed items after remediation

### ISSUE THREAD

**Issue by ykhodorkovskiy** [TresysTechnology/clip#77]
Basically if you run SSG on a system in the field, you should have a ton of "Pass" items and few/none "FAIL" items.

Because CLIP is a developer baseline, many of those field configuration items don't aren't practical (i.e. we need a privileged user and some access to the system for development).

This means that if you run SSG on a CLIP system, there are likely some items which you would expect to see "FAIL" on.

It would be nice to have some documentation along with CLIP saying, "We know these are FAIL items out-of-the-box; that is done by design to make this system accessible to developers.  These items should be addressed during the course of system development."

**Comment by minapoli** [comment]
There should be no failures after remediation. Rules that are not applicable are not checked.
