### ISSUE TITLE
local packages should be rebuilt only when changes have been made

### ISSUE THREAD

**Issue by ykhodorkovskiy** [TresysTechnology/clip#97]
The build system is rebuilding the packages/ directory every time we run make. We need a better way to determine if there are changes within that directory, and then rebuild the rpms only in that case.

**Comment by mpalmi** [comment]
It seems as if packages are not being rebuilt when there are changes.
I am not seeing my selinux policy changes make it into a build after the following steps:

1) make
2) Edit package contents
3) make
